<a href="https://colab.research.google.com/github/sivaait023/DS_GUI_Task/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
null_vect=np.zeros(10)
null_vect

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
arr1=np.array([1,7,3,4,5])
print('length of whole array(arr1):',arr1.size)
print('size of single element in array',arr1.itemsize)
print('size of an array',arr1.size*arr1.itemsize)

length of whole array(arr1): 5
size of single element in array 8
size of an array 40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arr2=np.zeros(10)
arr2[4]=1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr3=np.arange(0,50)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
reverse=arr3[::-1]
reverse

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
arr4=np.arange(0,9)
arr4.reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arr5=np.array([1,2,0,0,4,0])
np.nonzero(arr5)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
arr6=np.eye(3,3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
_3darray=np.random.random((3,3,3))
_3darray

array([[[0.84784568, 0.611805  , 0.39486165],
        [0.35329966, 0.17088452, 0.88144331],
        [0.36859872, 0.820183  , 0.70795217]],

       [[0.8688438 , 0.74573532, 0.19085084],
        [0.65696833, 0.18187976, 0.87544231],
        [0.21850811, 0.7269759 , 0.85505563]],

       [[0.35504499, 0.45725462, 0.98211786],
        [0.04399201, 0.80093432, 0.18902351],
        [0.81123929, 0.37561786, 0.59396139]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr7=np.random.randint(0,200,(10,10))
print('MINIMUM IS:{}\nMaximum is :{}'.format(arr7.min(),arr7.max()))

MINIMUM IS:5
Maximum is :197


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
np.random.seed(0)
arr8=np.random.randint(0,10,30)
print('MEAN of the vector is',arr8.mean())
arr8

MEAN of the vector is 4.866666666666666


array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6, 8, 8, 1, 6, 7, 7, 8, 1, 5, 9,
       8, 9, 4, 3, 0, 3, 5, 0])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
arr9=np.ones((5,5))
arr9[1:-1,1:-1]=0
arr9

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
arr10=np.pad(arr9,[],mode='constant')
arr10

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2, 1::2]=1
checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
np.random.seed(0)
array=np.random.randint(0,100,(5,5))
min=array.min()
max=array.max()
Normalizedmatrix=(array-min)/(min-max)
print('5*5 random matix (before normalization):\n',array)
print('5*5 random matix (after normalization):\n',Normalizedmatrix)

5*5 random matix (before normalization):
 [[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]]
5*5 random matix (after normalization):
 [[-0.44303797 -0.48101266 -0.69620253 -0.73417722 -0.73417722]
 [-0.         -0.93670886 -0.15189873 -0.34177215 -0.98734177]
 [-0.7721519  -1.         -1.         -0.03797468 -0.62025316]
 [-0.70886076 -0.37974684 -0.98734177 -0.46835443 -1.        ]
 [-0.91139241 -0.35443038 -0.20253165 -0.86075949 -0.79746835]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
colors=np.dtype([
    ("r",np.ubyte,(1,)),
    ("g",np.ubyte,(1,)),
    ("b",np.ubyte,(1,)),
    ("a",np.ubyte,(1,)),
])
colors

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
X=np.random.randint(1,100,(5,3))
Y=np.random.randint(1,100,(3,2))
print(np.dot(X,Y))
Matrixmultiplication=X@Y
print(Matrixmultiplication)

[[2114 1200]
 [1600 2607]
 [8276 5745]
 [6214 2862]
 [8926 6147]]
[[2114 1200]
 [1600 2607]
 [8276 5745]
 [6214 2862]
 [8926 6147]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
np.random.seed(0)
arr11=np.random.randint(0,20,10)
arr11[4:9]*=-1
arr11

array([ 12,  15,   0,   3,  -3,  -7,  -9, -19, -18,   4])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.random.randint(0,100,10,dtype=int)
print(Z**Z) #legal
print(2 << Z >> 2) #legal
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[-5821812116355782473                    0             16777216
 -2101438300051996672 -1902703244836818301 -8206467232675302283
 -5296008294479953920 -4053175462519618527  8037740809528595931
 -8795647696940200745]
[                0 36028797018963968               128            524288
                 0                 0        8589934592        4294967296
                 0      274877906944]
[False False False False False False False False False False]
[0.+71.j 0.+56.j 0. +8.j 0.+20.j 0.+91.j 0.+69.j 0.+34.j 0.+33.j 0.+67.j
 0.+39.j]
[71. 56.  8. 20. 91. 69. 34. 33. 67. 39.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-10-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-10-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
S=np.random.randint(-20,10,10)
result=np.copysign(np.ceil(np.ceil(S)),S)
print(result)

[  1. -17.   2.   5.  -2.   3.   4.   5. -15. -13.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
X=np.random.randint(0,10,10)
Y=np.random.randint(1,10,10)
np.intersect1d(X,Y)

array([6, 7, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
x=np.array([1])
y=np.array([0])
x/y

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)
print('No it is not true')

No it is not true


<ipython-input-33-ee1549ef1cc1>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('Yesterday:{}\ntoday:{}\ntommorrow:{}'.format(yesterday,today,tomorrow))

Yesterday:2022-12-28
today:2022-12-29
tommorrow:2022-12-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
Range=np.arange('2016-07','2016-08',dtype="datetime64[D]")
Range

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=5*np.ones((3,3))
B=3*np.ones((3,3))
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[-20., -20., -20.],
       [-20., -20., -20.],
       [-20., -20., -20.]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.randn(10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[-2. -1.  1.  1.  0. -1. -1. -2. -1. -1.]
[-2. -1.  1.  1.  0. -1. -1. -2. -1. -1.]
[-2. -1.  1.  1.  0. -1. -1. -2. -1. -1.]
[-1  0  1  1  0  0  0 -1  0  0]
[-1. -0.  1.  1.  0. -0. -0. -1. -0. -0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
matrix=np.ones((5,5))
matrix*=np.arange(0,5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iter=[x*x for x in range(10)]
MX=np.fromiter(iter,dtype=float)
MX

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Vector=np.linspace(0,1,11,endpoint=False)
Vector

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
arr13=np.random.randint(0,20,10)
print(arr13)
np.sort(arr13)

[16  5  8  2 14 14 13  6  5 15]


array([ 2,  5,  5,  6,  8, 13, 14, 14, 15, 16])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:

np.add.reduce([3,4,56])

63

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.randint(0,10,10)
C=np.random.randint(0,10,10)
#np.allclose(A,C)
np.array_equal(a1=A,a2=C)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
B=np.array([4,5,6,7])
B.flags.writeable=False
B[0]=0
B

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Cc=np.random.randint(0,20,(10,2))
x,y=Cc[:,0],Cc[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(x,y)
print(r)
print(t)

[18.97366596 16.64331698 18.60107524  7.81024968 20.61552813 24.8394847
 13.03840481 15.8113883  10.04987562 15.26433752]
[0.32175055 0.99945885 0.63274884 0.87605805 0.39852245 0.87090346
 0.56672922 1.24904577 1.47112767 0.55165498]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
randvect=np.random.randint(0,100,10)
randvect[randvect.argmax()]=0
randvect

array([18, 76, 10, 64,  0, 74, 40, 50, 71, 61])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
arrays=np.ones((5,5),[('x',float),('y',float)])
arrays['x'],arrays['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arrays)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X=np.arange(8)
Y=X+0.8
CauchyMatrix=1/np.subtract.outer(X,Y)
print(np.linalg.det(CauchyMatrix))

41846.73328656058


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print('datatype :',dtype)
   print("Minimum value:",np.iinfo(dtype).min)
   print("Maximum value:",np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print('datatype :',dtype)
   print("Minimum value:",np.finfo(dtype).min)
   print("Maximum value:",np.finfo(dtype).max)

datatype : <class 'numpy.int8'>
Minimum value: -128
Maximum value: 127
datatype : <class 'numpy.int32'>
Minimum value: -2147483648
Maximum value: 2147483647
datatype : <class 'numpy.int64'>
Minimum value: -9223372036854775808
Maximum value: 9223372036854775807
datatype : <class 'numpy.float32'>
Minimum value: -3.4028235e+38
Maximum value: 3.4028235e+38
datatype : <class 'numpy.float64'>
Minimum value: -1.7976931348623157e+308
Maximum value: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((200,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
np.random.seed(0)
vect4=np.random.randint(1,90,10)
print(vect4)
vect4[vect4.argmin()]

[45 48 65 68 68 10 84 22 37 88]


10

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
X=np.array([3.5,4.6,7.8],dtype=np.float32)
X=X.astype(np.int32)
X

array([3, 4, 7], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from os import replace
from io import StringIO
x=StringIO("""1, 2, 3, 4, 5\n
6,  ,  , 7, 8\n
 ,  , 9,10,11\n""")
arr40=np.genfromtxt(x,delimiter=",",dtype='int64')
arr40

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z2=np.arange(10).reshape(5,2)
for index,value in np.ndenumerate(Z2):
  print(index,value)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
import numpy as np
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
dst=np.sqrt(X**2+Y**2)
sigma,mu=1.0,0.0
G = np.exp(-( (dst-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=10
p=3
arr21=np.zeros((n,n))
np.put(arr21,np.random.choice(range(n*n),p,replace=False),1)
print(arr21)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
M=np.random.randint(0,100,(5,5))
N=M-M.mean(axis=1,keepdims=True)
print(N)

[[-23.2  28.8  18.8  -9.2 -15.2]
 [ 36.8 -31.2   2.8 -10.2   1.8]
 [ 43.6  16.6 -50.4  -3.4  -6.4]
 [ -9.2 -16.2 -36.2  22.8  38.8]
 [-46.8 -26.8  26.2  37.2  10.2]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 6 8]
 [0 5 0]
 [2 3 1]]
[[2 3 1]
 [0 5 0]
 [9 6 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z1=np.array([[34,0,57,90]
             ,[90,0,34,56],[45,67,8,10]])
print(~Z1.any(axis=0).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr19=np.array([45,56,78,90,12,34])
value=10
diff_array=np.abs(arr19-value)
index=diff_array.argmin()
print("Nearest element to the given values is : ", arr19[index])
print("Index of nearest value is : ", index)

Nearest element to the given values is :  12
Index of nearest value is :  4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
iter_=np.nditer([A,B,None])
for x,y,z in iter_: z[...]=x+y
print(iter_.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z=np.ones(10)
I=np.random.randint(0,len(Z),20)
np.add.at(Z,I,1)
print(Z)

[4. 1. 4. 4. 2. 3. 4. 3. 4. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X=[1,2,3,4,5,6]
I=[1,3,2,1,3,4]
F=np.bincount(I,X)
print(F)

[0. 5. 3. 7. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0] * 256*256 + I[...,1] * 256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
arr31=np.random.randint(0,50,(3,4,4,8))
SUM=arr31.sum(axis=(-2,-1))
print(SUM)

[[818 696 863 818]
 [821 745 697 815]
 [756 894 777 766]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D=np.random.randint(0,20,100)
S=np.random.randint(0,10,100)
Sum_d=np.bincount(S,weights=D)
counts_d=np.bincount(S)
mean=Sum_d/counts_d
print(mean)

[ 8.875       9.          8.14285714  7.33333333  6.2        11.63636364
  9.77777778  8.8        10.18181818  7.35714286]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
np.random.seed(0)
A4=np.random.randn(5,5)
A5=np.random.randn(5,5)
dot_product=np.diag(np.dot(A4, A5))
print(dot_product)

[-5.51837355 -0.2394676  -0.26550057 -0.37940614 -4.34460348]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
nums = np.array([1,2,3,4,5,6,7,8])
print("Original array:")
print(nums)
p = 3
new_nums = np.zeros(len(nums) + (len(nums)-1)*(p))
new_nums[::p+1] = nums
print("New array:")
print(new_nums)

Original array:
[1 2 3 4 5 6 7 8]
New array:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0. 6. 0. 0. 0.
 7. 0. 0. 0. 8.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
arr_1=np.random.randint(0,50,(5,5,3))
arr_2=np.random.randint(0,50,(5,5))
result=arr_1*arr_2[:,:,None]
print(result)


[[[1720  720 1800]
  [ 690   30  180]
  [1134 1296  810]
  [ 688 1118 1505]
  [1519 1302  279]]

 [[ 880  260  120]
  [ 228  234   48]
  [ 117   63  144]
  [ 594  405  675]
  [ 376 1645  282]]

 [[ 595  245  700]
  [ 475   38  304]
  [ 540  276  288]
  [  72  648  792]
  [2401 1127 1470]]

 [[ 250  200  330]
  [1258  782  918]
  [ 957 1089  726]
  [ 301 1763 2107]
  [  27    0   57]]

 [[ 432  204  240]
  [1728  108 1512]
  [   1   20   36]
  [ 196  784 2352]
  [   0    0    0]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
arr14=np.array([[3,4,5,6],
                [6,7,8,9],
                [9,4,5,6]]
                )
arr14[[0,1]]=arr14[[1,0]]

arr14

array([[6, 7, 8, 9],
       [3, 4, 5, 6],
       [9, 4, 5, 6]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 47) ( 0, 60) ( 6, 71) ( 6, 94) ( 7, 43) ( 7, 82) (10, 13) (10, 75)
 (13, 75) (15, 30) (15, 45) (22, 76) (22, 79) (26, 55) (26, 90) (30, 45)
 (38, 41) (38, 53) (41, 53) (43, 82) (46, 61) (46, 80) (47, 60) (51, 90)
 (51, 98) (55, 90) (61, 80) (71, 94) (76, 79) (90, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C=np.bincount([1,1,1,2,2,4,4,6])
A=np.repeat(np.arange(len(C)),C)
print(A)

[1 1 1 2 2 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [35]:
def moving_average(a,n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]=ret[n:]-ret[:-n]
  return ret[n-1:]/n
Z=np.arange(20)
average=moving_average(Z,n=3)
average

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [4]:
from numpy.lib import stride_tricks
import numpy as np
a=np.random.randint(0,10,20)
window=3
shape = (a.size - window + 1, window)
strides = (a.itemsize, a.itemsize)
Z= stride_tricks.as_strided(a, shape=shape, strides=strides)
print(Z)

[[3 0 3]
 [0 3 9]
 [3 9 3]
 [9 3 2]
 [3 2 9]
 [2 9 0]
 [9 0 9]
 [0 9 6]
 [9 6 0]
 [6 0 7]
 [0 7 7]
 [7 7 5]
 [7 5 0]
 [5 0 4]
 [0 4 3]
 [4 3 6]
 [3 6 3]
 [6 3 1]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [9]:
Z = np.random.randint(0,10,100)
logical=np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,50)
negative=np.negative(Z, out=Z)
print("Logical_not:",logical)
print("Negative",negative)

Logical_not: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0]
Negative [ 0.05310241  0.19678509  0.70172963  0.07854313 -0.069584    0.41708719
  0.94778447  0.78912036 -0.30357139  0.3894937   0.04099281  0.9944634
  0.54990106 -0.43274947  0.07449725 -0.65044565  0.22881691 -0.01291861
 -0.95384285 -0.39105873 -0.49833219 -0.14623951  0.20055714 -0.57897631
 -0.39577118 -0.46884303  0.58616169 -0.14573213 -0.43472504  0.22021159
  0.1240047   0.9890378  -0.23154918  0.43900421 -0.42715898 -0.56398983
  0.37927141 -0.79433307 -0.77770153 -0.22670951  0.027958    0.70320096
 -0.97967813 -0.71623164  0.75740167 -0.47337159  0.38551859  0.26205621
 -0.3554024   0.5296397 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [16]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.08995415  1.50827839  3.24900021  3.79022737  8.39232439  0.90197749
  2.53460611  9.90669737 16.78484337  0.0169681 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [18]:
p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[2.59061763e+00 6.31774875e-01 2.36214800e+00 3.46944459e+00
  7.03194093e-01 2.67644783e+00 4.58415503e+00 4.79753422e+00
  6.64739062e+00 2.65467642e+00]
 [2.88371305e+00 1.54410846e+00 8.89900752e+00 6.69213599e+00
  9.71498143e+00 3.02472059e+00 1.43475715e+01 1.52364803e+00
  1.70525400e+01 3.18103110e+00]
 [1.67948043e+00 8.88391599e-01 5.19195232e+00 1.05591108e-02
  2.70386634e+00 1.68014702e+00 7.32987099e+00 4.67851350e+00
  9.83450883e+00 1.81697179e-04]
 [5.53874464e+00 5.47145139e+00 3.98457844e+00 3.41598064e+00
  7.00205142e+00 5.56971488e+00 1.38809371e+01 2.04092015e+00
  1.53441059e+01 1.80309321e+00]
 [4.28860964e+00 9.40905314e+00 9.99125284e+00 1.15724276e+01
  7.36747285e+00 3.92801290e+00 3.61956943e+00 4.34541533e+00
  2.53827095e+00 1.52013648e+01]
 [6.17195516e+00 1.55342655e+00 3.32692932e+00 1.15507500e+01
  8.87569913e+00 6.44463297e+00 2.71202967e+00 6.59393869e+00
  1.33997653e+00 7.83781691e+00]
 [1.32311900e+00 1.60971304e+00 1.01593482e+00 6.08070305e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
Z=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(Z,(11,4),strides=(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z=np.random.randint(10,20,50)
print(np.bincount(Z).argmax())

10


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [10]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 0 4]
   [1 1 0]
   [1 4 1]]

  [[0 4 2]
   [1 0 2]
   [4 1 0]]

  [[4 2 1]
   [0 2 4]
   [1 0 3]]

  [[2 1 3]
   [2 4 0]
   [0 3 2]]

  [[1 3 2]
   [4 0 2]
   [3 2 3]]

  [[3 2 3]
   [0 2 2]
   [2 3 1]]

  [[2 3 1]
   [2 2 2]
   [3 1 4]]

  [[3 1 0]
   [2 2 1]
   [1 4 0]]]


 [[[1 1 0]
   [1 4 1]
   [4 4 0]]

  [[1 0 2]
   [4 1 0]
   [4 0 1]]

  [[0 2 4]
   [1 0 3]
   [0 1 0]]

  [[2 4 0]
   [0 3 2]
   [1 0 0]]

  [[4 0 2]
   [3 2 3]
   [0 0 1]]

  [[0 2 2]
   [2 3 1]
   [0 1 0]]

  [[2 2 2]
   [3 1 4]
   [1 0 4]]

  [[2 2 1]
   [1 4 0]
   [0 4 1]]]


 [[[1 4 1]
   [4 4 0]
   [1 2 1]]

  [[4 1 0]
   [4 0 1]
   [2 1 0]]

  [[1 0 3]
   [0 1 0]
   [1 0 3]]

  [[0 3 2]
   [1 0 0]
   [0 3 0]]

  [[3 2 3]
   [0 0 1]
   [3 0 2]]

  [[2 3 1]
   [0 1 0]
   [0 2 3]]

  [[3 1 4]
   [1 0 4]
   [2 3 2]]

  [[1 4 0]
   [0 4 1]
   [3 2 2]]]


 [[[4 4 0]
   [1 2 1]
   [1 4 3]]

  [[4 0 1]
   [2 1 0]
   [4 3 3]]

  [[0 1 0]
   [1 0 3]
   [3 3 4]]

  [[1 0 0]
   [0 3 0]
   [3 4 2]]

  [[0 0 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [11]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [14]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [22]:
from numpy.lib.npyio import NpzFile
Z=np.arange(10000)
np.random.shuffle(Z)
n=5
print(Z[np.argsort(Z)[-n:]])
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [23]:
def cartesian(arrays):
  arrays=[np.asarray(a) for a in arrays]
  shape=(len(x) for x in arrays)

  ix=np.indices(shape,dtype=int)
  ix=ix.reshape(len(arrays),-1).T

  for n ,arr in enumerate(arrays):
    ix[:,n]=arrays[n][ix[:,n]]
    return ix

m=cartesian(([1,2,3],[6,7],[9,10]))
print(m)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [33]:
Z__1=np.array([("Hello",2.5,3),
            ("world",3.4,8)
            ])
Record_array=np.core.records.fromarrays(Z__1.T,names='col1,col2,col3',formats='S8,f8,i8')
print(Record_array)

[(b'Hello', 2.5, 3) (b'world', 3.4, 8)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [31]:
X=np.random.randint(1,300,10000)

c_1=np.power(X,3)
c_2=X*X
c_3=np.einsum('i,i,i->i',X,X,X)
c_1,c_2,c_3

(array([  941192,  3581577,  3511808, ...,   117649, 10793861, 20123648]),
 array([ 9604, 23409, 23104, ...,  2401, 48841, 73984]),
 array([  941192,  3581577,  3511808, ...,   117649, 10793861, 20123648]))

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [58]:
A = np.random.randint(0,10,(8,3))
B = np.random.randint(0,10,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [48]:
matrix_2=np.array([2,3,4,7,8,9,11,23,45],dtype=np.uint8)
print(np.unpackbits(matrix_2[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 1 1]
 [0 0 0 1 0 1 1 1]
 [0 0 1 0 1 1 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [39]:
Z__3=np.random.randint(0,100,(5,5))
unique=np.unique(Z,axis=0)
print(unique)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [44]:
A=np.random.randint(0,20,10)
B=np.random.randint(50,100,10)
print('sum')
print(np.einsum('i->',A))
print('multiply')
print(np.einsum('i,i->i',A,B))
print('inner')
print(np.einsum('i,i',A,B))
print('outer')
print(np.einsum('i,j->ij',A,B))

sum
118
multiply
[ 855 1692 1157  540  960  912  148  854  952 1104]
inner
9174
outer
[[ 855  846  801  486  864  684  666  549  612  621]
 [1710 1692 1602  972 1728 1368 1332 1098 1224 1242]
 [1235 1222 1157  702 1248  988  962  793  884  897]
 [ 950  940  890  540  960  760  740  610  680  690]
 [ 950  940  890  540  960  760  740  610  680  690]
 [1140 1128 1068  648 1152  912  888  732  816  828]
 [ 190  188  178  108  192  152  148  122  136  138]
 [1330 1316 1246  756 1344 1064 1036  854  952  966]
 [1330 1316 1246  756 1344 1064 1036  854  952  966]
 [1520 1504 1424  864 1536 1216 1184  976 1088 1104]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [59]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [62]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means,[2.5.97.5])
print(confint)


SyntaxError: ignored